# Generated by Django 3.0.7 on 2020-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_title', models.CharField(max_length=50)),
                ('certificate_description', models.TextField()),
                ('imgcertificate', models.ImageField(upload_to='certificate_folder')),
                ('certificate_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_title', models.CharField(max_length=50)),
                ('design_description', models.TextField()),
                ('imgcdesign', models.ImageField(upload_to='design_folder')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('imgproject', models.ImageField(upload_to='project_folder')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
