# Generated by Django 3.0.7 on 2020-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200806_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(default='', upload_to='project_folder'),
            preserve_default=False,
        ),
    ]
